# Generated by Django 2.2.5 on 2020-01-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200119_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='istg',
            field=models.TextField(default='-'),
        ),
    ]
