# Generated by Django 2.2.5 on 2020-01-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_main_set_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='footer_link',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='phone',
            field=models.TextField(default='-'),
        ),
    ]
