# Generated by Django 2.2.5 on 2020-01-19 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200120_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='setname',
            new_name='set_name',
        ),
    ]
