# Generated by Django 2.2.5 on 2020-01-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200120_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='about',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='main',
            name='fb',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='main',
            name='istg',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='main',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='set_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='main',
            name='twt',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='main',
            name='website',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='main',
            name='ytb',
            field=models.CharField(max_length=150),
        ),
    ]
